### ISSUE TITLE
[ansible] Stricter Requirements Around Including Role Variables

### ISSUE THREAD

**Issue by ekultails** [ekultails/rootpages#125]
Starting in Ansible 2.5, the syntax for defining variables for a Role inside of a Playbook have changed to remove a legacy way of adding variables.

Before (no longer works):
```
---
- hosts: all
  roles:
    - example
        some_var: 123
```

After:
```
---
- hosts: all
  roles:
    - role: example
        vars:
          some_var: 123
```

As another alternative, `import_role` and `include_role` can also be used instead of `role` if it's used inside of a `tasks` dictionary (instead of `roles`).

https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html
