### ISSUE TITLE
[virtualization][kubernetes_development] Known issues with httpGet probes

### ISSUE THREAD

**Issue by ekultails** [ekultails/rootpages#372]
https://github.com/kubernetes/kubernetes/issues/89898

**Comment by ekultails** [comment]
Workaround:

```
kind: Pod
spec:
  containers:
    - <PROBE_TYPE>Probe:
      exec:
        command:
          - curl
          - --fail
          - http://127.0.0.1:<PORT>
```
