### ISSUE TITLE
[virtualization][kubernetes_administration] Add CAs to TKGS

### ISSUE THREAD

**Issue by ekultails** [ekultails/rootpages#436]
Here is the example provided in the article. Only the `TkgServiceConfiguration.spec.trust.additionalTrustedCAs.{name,data}` parameters are required.

```
apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TkgServiceConfiguration
metadata:
  name: tkg-service-configuration
spec:
  defaultCNI: antrea
  proxy:
    httpProxy: http://<user>:<pwd>@<ip>:<port>

  trust:
    additionalTrustedCAs:
      - name: first-cert-name
        data: base64-encoded string of a PEM encoded public cert 1
      - name: second-cert-name
        data: base64-encoded string of a PEM encoded public cert 2
```

https://brianragazzi.wordpress.com/2021/03/22/adding-trusted-certs-to-nodes-on-tkgs-7-0-u2/
