### ISSUE TITLE
[virtualization][kubernetes_administration] cert-manager use container registry proxy

### ISSUE THREAD

**Issue by ekultails** [ekultails/rootpages#444]
These are the values required for the Helm chart:

```
---
image:
  registry: <QUAY_IO_PROXY>
  repository: jetstack/cert-manager-controller
cainjector:
  image:
    registry: <QUAY_IO_PROXY>
    repository: jetstack/cert-manager-cainjector
webhook:
  image:
    registry: <QUAY_IO_PROXY>
    repository: jetstack/cert-manager-webhook
```

The containers are NOT hosted on Docker Hub. They are only on Quay.

https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
