### ISSUE TITLE
[virtualization][kubernetes_administration] Troubleshoot Let-s Encrypt issues

### ISSUE THREAD

**Issue by ekultails** [ekultails/rootpages#485]
https://cert-manager.io/docs/faq/acme/

**Comment by ekultails** [comment]
If the certificate Secret already exists, delete it force it to be re-created. It will be re-created instantly.

**Comment by ekultails** [comment]
Error checking the Order related to a TLS secret for the certificate-to-be-created:

```
$ kubectl describe order <SECRET_NAME>-<RANDOM_UUID>
Failed to determine a valid solver configuration for the set of domains on the Order: both ingress name and ingress class overrides specified - only one may be specified at a time
```

Fix:

- Only one `ingress.annotations.acme.cert-manager.io/http01*` annotation can be used. Typically, the usage of the variable should be one of these:

```
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "clusterissuer-letsencrypt-staging"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issue-temporary-certificate: "true"
```

```
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "clusterissuer-letsencrypt-staging"
    acme.cert-manager.io/http01-ingress-class: nginx
```

Source: https://github.com/jetstack/cert-manager/issues/2545

**Comment by ekultails** [comment]
Error:

```
$ kubectl describe cm-acme-http-solver-<RANDOM_UUID>
<OMITTED>
Events:
  Type     Reason    Age   From                      Message
  ----     ------    ----  ----                      -------
  Warning  Rejected  72s   nginx-ingress-controller  All hosts are taken by other resources
  Warning  Rejected  72s   nginx-ingress-controller  All hosts are taken by other resources
  Warning  Rejected  72s   nginx-ingress-controller  All hosts are taken by other resources
```

Fix:

- The Ingress Controller does not support more than one Ingress object per domain name. Set the annotations that tell cert-manager to instead modify Ingress object that the annotation itself is in. This will add a new path that includes a token that ACME / Let's Encrypt will look for to verify you own the domain.

```
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "clusterissuer-letsencrypt-staging"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issue-temporary-certificate: "true"
```

Source: https://cert-manager.io/docs/faq/acme/
