### ISSUE TITLE
[virtualization][kubernetes_administration] Minimal PSP object manifest

### ISSUE THREAD

**Issue by ekultails** [ekultails/rootpages#500]
Every PodSecurityPolicy needs to include at least these spec values (fsGroup, runAsUser, seLinux, and supllementalGroups) even if they are not being modified:

```yaml
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-minimal
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
```

https://kubernetes.io/docs/concepts/policy/pod-security-policy/
