### ISSUE TITLE
[virtualization][kubernetes_development] Helm set annotations with periods in the key name

### ISSUE THREAD

**Issue by LukeShortCloud** [ekultails/rootpages#577]
Quote the string and escape any periods.

Example:

`helm template --set "ingress.annotations.cert-manager\.io/cluster-issuer"=self-signed harbor bitnami/harbor`

Renders out to be:

```
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: self-signed
```
