### ISSUE TITLE
[virtualization][kubernetes_development] Use HostAliases in Pods

### ISSUE THREAD

**Issue by LukeShortCloud** [ekultails/rootpages#579]
Example from documentation:

```
apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "foo.local"
    - "bar.local"
  - ip: "10.1.2.3"
    hostnames:
    - "foo.remote"
    - "bar.remote"
  containers:
  - name: cat-hosts
    image: busybox
    command:
    - cat
    args:
    - "/etc/hosts"
```

https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
